name: codex_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  highlight: ^0.7.0
  flutter_highlighting: ^0.9.0+11.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Dart-logo.png
    - assets/eclipse.png
    - assets/flutter-logo.png
    - assets/git-img.png
    - assets/github.png
    - assets/hibernate-logo.png
    - assets/java-14-logo.png
    - assets/js-logo.png
    - assets/maria.png
    - assets/mysql-img.png
    - assets/oracle.png
    - assets/postman.png
    - assets/Python-logo.png
    - assets/react-logo.png
    - assets/spring-logo.png
    - assets/vs-logo.png
    - assets/apple.png
    - assets/google.png
    - assets/CodeX-Logo.jpg
    - assets/mongodb.png
